name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@guiisn'
      - run: npm install

      # Increment version using standard-version
      - name: Increment Version
        run: npm run release

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
