name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@guiisn'
      - run: npm install --loglevel=error

      - name: Run unit tests
        run: npm run test

      - name: Set git identity
        run: |
          git config user.email "glhrmsouzanunes@gmail.com"
          git config user.name "guiisn"

      - name: Increment Version
        run: npm run release

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
